### ISSUE TITLE
Add screenshot to README?

### ISSUE THREAD

**Issue by dandv** [tidepool-org/jellyfish#57]
I've just learned about the Tidepool platform, and I'm looking through the repos to figure out what each app does. Jellyfish's README could use some fleshing out... a screenshot would help. Thanks!

**Comment by kentquirk** [comment]
Hi, Dan. Thanks. 

Jellyfish's readme does need updating, but a screenshot would be meaningless, as it no longer has a client (all uploads are now done with our uploader app). I'm going to close this issue and open a bug in our trello boards to update documentation.
